export enum ROLE {
    COMPANY_ADMIN = 'COMPANY_ADMIN',
    SUPER_ADMIN = 'SUPER_ADMIN',
    TRANSPORT_COMPANY_MANAGER = 'TRANSPORT_COMPANY_MANAGER',
    DISPACHER = 'DISPACHER',
    DRIVER = 'DRIVER',
    CONDUCTOR = 'CONDUCTOR',
    CHECKER = 'CHECKER',
    MAKER = 'MAKER',
    PASSANGER = 'PASSANGER'
}